const List<String> kStickerAssets = [
  'assets/core/stickers/696e3fea1967d56f4fc07fa06d0a7c7a.png',
  'assets/core/stickers/Anggry Fire Emoji.png',
  'assets/core/stickers/Crazy Love Emoji.png',
  'assets/core/stickers/Crying laugh emoji.png',
  'assets/core/stickers/arrow (1).png',
  'assets/core/stickers/arrow (2).png',
  'assets/core/stickers/arrow-right.png',
  'assets/core/stickers/arrow.png',
  'assets/core/stickers/arrows.png',
  'assets/core/stickers/border-design.png',
  'assets/core/stickers/border-style.png',
  'assets/core/stickers/capture.png',
  'assets/core/stickers/curved-arrow-with-broken-line.png',
  'assets/core/stickers/decorative-frame.png',
  'assets/core/stickers/down-arrow.png',
  'assets/core/stickers/fast-forward (1).png',
  'assets/core/stickers/fast-forward.png',
  'assets/core/stickers/flower.png',
  'assets/core/stickers/frame (1).png',
  'assets/core/stickers/frame (2).png',
  'assets/core/stickers/frame (3).png',
  'assets/core/stickers/frame (4).png',
  'assets/core/stickers/frame (5).png',
  'assets/core/stickers/frame (6).png',
  'assets/core/stickers/frame (7).png',
  'assets/core/stickers/frame (8).png',
  'assets/core/stickers/frame.png',
  'assets/core/stickers/holy_shrine.png',
  'assets/core/stickers/islam.png',
  'assets/core/stickers/photo-frame.png',
  'assets/core/stickers/photo.png',
  'assets/core/stickers/rating.png',
  'assets/core/stickers/right-arrow (1).png',
  'assets/core/stickers/right-arrow.png',
  'assets/core/stickers/sparkler.png',
  'assets/core/stickers/star (1).png',
  'assets/core/stickers/star (2).png',
  'assets/core/stickers/star (3).png',
  'assets/core/stickers/star (4).png',
  'assets/core/stickers/star.png',
  'assets/core/stickers/video (1).png',
  'assets/core/stickers/video.png',
];
